Repository openkruise/kruise-game, pull requests merged in 2022-11, with the labels that each got.

#11 Add feature: Service Quality
  .github/workflows/e2e-1.24.yaml
  apis/v1alpha1/gameserver_types.go
  apis/v1alpha1/gameserverset_types.go
  config/crd/bases/game.kruise.io_gameserversets.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  main.go
  pkg/controllers/gameserver/gameserver_controller.go
  pkg/controllers/gameserver/gameserver_manager.go
  pkg/controllers/gameserver/gameserver_manager_test.go
  pkg/controllers/gameserverset/gameserverset_controller.go
  pkg/controllers/gameserverset/gameserverset_manager.go
  pkg/util/gameserver.go
  pkg/util/gameserver_test.go
  pkg/util/pod.go
  pkg/util/pod_test.go
  pkg/webhook/webhook.go
  test/e2e/framework/framework.go
  test/e2e/testcase/testcase.go
Labels: lgtm, size/XL

#10 Refactoring GameServer Lifecycle Management
  apis/v1alpha1/gameserver_types.go
  pkg/controllers/gameserver/gameserver_controller.go
  pkg/controllers/gameserverset/gameserverset_manager.go
  test/e2e/client/client.go
  test/e2e/framework/framework.go
  test/e2e/testcase/testcase.go
Labels: lgtm, size/L

#13 Feat: add ObservedGeneration to GameServerSet
  apis/v1alpha1/gameserverset_types.go
  config/crd/bases/game.kruise.io_gameserversets.yaml
  pkg/controllers/gameserverset/gameserverset_manager.go
Labels: lgtm, size/S, approved

#17 Feature/update docs
  README.md
  docs/en/getting_started/architecture.md
  docs/en/getting_started/installation.md
  docs/en/getting_started/introduction.md
  docs/en/tutorials/basic_usage.md
  docs/images/okg.png
  docs/images/workload.png
  docs/proposals/YYYYMMDD-template.md
  docs/中文/常见问题/常见问题.md
  docs/中文/开发者手册/如何贡献代码.md
  docs/中文/核心概念/OpenKruiseGame的设计理念.md
  docs/中文/说明文档.md
Labels: size/L

#19 Feat: update docs(CN)
  docs/images/hot-update.png
  docs/images/update-priority.png
  docs/images/warning-ding.png
  docs/中文/快速开始/安装OpenKruiseGame.md
  docs/中文/快速开始/游戏服水平伸缩.md
  docs/中文/快速开始/游戏服热更新.md
  docs/中文/快速开始/部署游戏服.md
  docs/中文/用户手册/游戏服更新策略.md
  docs/中文/用户手册/网络模型.md
  docs/中文/用户手册/自定义服务质量.md
  docs/中文/说明文档.md
Labels: lgtm, size/XL

#23 update docs design concept(zh_CN)
  docs/中文/核心概念/OpenKruiseGame的设计理念.md
Labels: lgtm, size/XS
