Repository openkruise/kruise-game, pull requests merged in 2022-10, with the labels that each got.

#8 Add doc of architecture
  docs/getting_started/architecture.md
  docs/images/arch.png
Labels: size/M

#9 Add e2e test checker
  .github/workflows/e2e-1.24.yaml
  Makefile
  scripts/deploy_kind.sh
  test/e2e/framework/framework.go
  test/kind-conf.yaml
Labels: size/L

#12 Update README.md
  README.md
Labels: lgtm, size/S
