Repository openkruise/kruise-game, pull requests merged in 2023-10, with the labels that each got.

#99 add OKG users: wuduan & juren
  README.md
  docs/en/introduction.md
  docs/images/juren-logo.png
  docs/images/wuduan-logo.png
  docs/中文/说明文档.md
Labels: lgtm, size/S

#104 update go version to 1.19
  .github/workflows/ci.yaml
  .github/workflows/e2e-1.26.yaml
  go.mod
  pkg/webhook/util/writer/atomic/atomic_writer.go
  pkg/webhook/util/writer/fs.go
Labels: size/M

#108 add qps and burst settings
  config/manager/manager.yaml
  main.go
Labels: size/S

#100 hostport network not ready when no ports exist
  cloudprovider/kubernetes/hostPort.go
Labels: lgtm, size/M

#98 Add network plugin AlibabaCloud-NLB-SharedPort & support AllowNotReadyContainers
  apis/v1alpha1/gameserverset_types.go
  cloudprovider/alibabacloud/nlb_sp.go
  cloudprovider/alibabacloud/nlb_sp_test.go
  cloudprovider/alibabacloud/slb.go
  cloudprovider/alibabacloud/slb_sp.go
  cloudprovider/alibabacloud/slb_sp_test.go
  cloudprovider/utils/service.go
  cloudprovider/utils/service_test.go
  docs/en/user_manuals/network.md
  docs/中文/用户手册/网络模型.md
  pkg/util/gameserver.go
  pkg/util/gameserver_test.go
  pkg/util/pod.go
  pkg/util/pod_test.go
Labels: size/XXL, lgtm

#95 feat: add GameServerConditions
  apis/v1alpha1/gameserver_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/game.kruise.io_gameservers.yaml
  config/rbac/role.yaml
  pkg/controllers/gameserver/gameserver_conditions.go
  pkg/controllers/gameserver/gameserver_conditions_test.go
  pkg/controllers/gameserver/gameserver_manager.go
  pkg/webhook/webhook.go
Labels: size/XXL, lgtm
