Repository openkruise/kruise-game, pull requests merged in 2023-05, with the labels that each got.

#55 add users of OKG
  README.md
  docs/en/introduction.md
  docs/images/booming-logo.png
  docs/中文/说明文档.md
Labels: size/XS

#56 new grafana json
  config/prometheus/grafana.json
Labels: lgtm, size/L

#54 feat: add networkType kubernetes-ingress
  cloudprovider/kubernetes/ingress.go
  cloudprovider/kubernetes/ingress_test.go
  config/rbac/role.yaml
  docs/en/user_manuals/network.md
  docs/中文/用户手册/网络模型.md
  pkg/webhook/webhook.go
Labels: size/XXL, lgtm

#57 add params for network plugins
  CHANGELOG.md
  config/manager/manager.yaml
  pkg/controllers/gameserver/gameserver_manager.go
  pkg/util/env.go
  pkg/util/env_test.go
Labels: size/M

#59 Fix the issue of unable to complete scaling down from 1 to 0.
  apis/v1alpha1/groupversion_info.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/externalscaler/externalscaler.go
  pkg/webhook/util/writer/atomic/atomic_writer.go
Labels: lgtm, size/L
