Repository openkruise/kruise-game, pull requests merged in 2024-04, with the labels that each got.

#137 enhance: Add annotations config in clb plugin
  Makefile
  cloudprovider/volcengine/README.md
  cloudprovider/volcengine/README.zh_CN.md
  cloudprovider/volcengine/clb.go
  cloudprovider/volcengine/clb_test.go
Labels: lgtm, size/M

#140 feat: sync annotations from gs to pod
  pkg/controllers/gameserver/gameserver_manager.go
  pkg/controllers/gameserver/gameserver_manager_test.go
  pkg/util/gameserver.go
Labels: lgtm, size/M

#141 enhance: add AllocateLoadBalancerNodePorts in clb plugin
  cloudprovider/options/volcenginecloud_options.go
  cloudprovider/volcengine/README.md
  cloudprovider/volcengine/README.zh_CN.md
  cloudprovider/volcengine/clb.go
  cloudprovider/volcengine/clb_test.go
Labels: lgtm, size/M

#143 add v0.8.0 changelog
  CHANGELOG.md
Labels: lgtm, size/S

#144 add changelog in v0.8.0
  CHANGELOG.md
Labels: lgtm, size/XS
