Repository openkruise/kruise-game, pull requests merged in 2024-01, with the labels that each got.

#122 add "apiVersion: game.kruise.io/v1alpha1"
  docs/中文/最佳实践/PvP类型游戏部署实践.md
Labels: lgtm, size/XS

#124 fix: avoid patching gameserver continuously
  pkg/controllers/controller.go
  pkg/controllers/gameserver/gameserver_conditions.go
  pkg/controllers/gameserver/gameserver_controller.go
  pkg/controllers/gameserver/gameserver_controller_test.go
  pkg/controllers/gameserver/gameserver_manager.go
  pkg/controllers/gameserver/gameserver_manager_test.go
Labels: lgtm, size/XL

#127 feat(*): add volcengine cloud provider and clb plugin
  cloudprovider/config.go
  cloudprovider/manager/provider_manager.go
  cloudprovider/options/volcenginecloud_options.go
  cloudprovider/volcengine/README.md
  cloudprovider/volcengine/README.zh_CN.md
  cloudprovider/volcengine/clb.go
  cloudprovider/volcengine/clb_test.go
  cloudprovider/volcengine/volcengine.go
  config/manager/config.toml
Labels: size/XXL, lgtm
