Repository openkruise/kruise-game, pull requests merged in 2025-04, with the labels that each got.

#213 feat: support multi groups for nlbs
  cloudprovider/alibabacloud/multi_nlbs.go
Labels: size/S

#209 feat(GameServerSet): support range type for ReserveIDs
  apis/v1alpha1/gameserverset_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/game.kruise.io_gameserversets.yaml
  go.mod
  go.sum
  pkg/controllers/gameserverset/gameserverset_controller_test.go
  pkg/controllers/gameserverset/gameserverset_manager.go
  pkg/controllers/gameserverset/gameserverset_manager_test.go
  pkg/util/gameserver.go
  pkg/util/set.go
  pkg/util/set_test.go
  pkg/util/slice.go
  pkg/util/slice_test.go
  pkg/webhook/validating_gss.go
  test/e2e/framework/framework.go
Labels: size/XXL, lgtm

#215 update ci workflow to ubuntu-24.04
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/XS

#212 ServiceQualities support serverless pod
  pkg/controllers/gameserverset/gameserverset_controller.go
  pkg/controllers/gameserverset/gameserverset_manager.go
  pkg/controllers/gameserverset/gameserverset_manager_test.go
Labels: lgtm, size/L

#216 enhance: support svc external traffic policy for AlibabaCloud-Multi-NLBs
  cloudprovider/alibabacloud/multi_nlbs.go
Labels: size/M

#214 enhance: add network ready condition for AlibabaCloud-Multi-NLBs plugin
  cloudprovider/alibabacloud/multi_nlbs.go
Labels: size/S

#218 feat(cloud_provider): add eip provider of VKE
  .gitignore
  cloudprovider/volcengine/eip.go
  cloudprovider/volcengine/eip_test.go
  go.mod
Labels: lgtm, size/L
