Repository openkruise/kruise-game, pull requests merged in 2025-08, with the labels that each got.

#275 feat: add balanced AllocatePolicy for AlibabaCloud-Multi-NLBs
  cloudprovider/alibabacloud/multi_nlbs.go
  cloudprovider/alibabacloud/multi_nlbs_test.go
Labels: size/L

#255 feat: enable leader election
  .github/workflows/e2e-1.30.yaml
  config/manager/manager.yaml
  config/manager/patches/add-leader-elect-patch.yaml
  main.go
  pkg/webhook/server.go
  pkg/webhook/server_test.go
  scripts/deploy_kind.sh
Labels: lgtm, size/L

#271 [DRAFT LFX] Enhance GameServerSet Unit Test Coverage
  pkg/controllers/gameserverset/gameserverset_controller_test.go
Labels: size/XXL, lgtm

#269 Add unit tests for `SetupWithManager` in `controller.go`
  pkg/controllers/controller_test.go
Labels: lgtm, size/L
