Repository openkruise/kruise-game, pull requests merged in 2025-07, with the labels that each got.

#253 fix the meaning of CURRENT printcolumn when using kubectl
  apis/v1alpha1/gameserverset_types.go
  config/crd/bases/game.kruise.io_gameserversets.yaml
Labels: size/XS

#254 feat: add PreDeleteReplicas for GameServerSet status
  apis/v1alpha1/gameserverset_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/game.kruise.io_gameserversets.yaml
  pkg/controllers/gameserverset/gameserverset_manager.go
Labels: size/S

#251 feat: 支持多 ingress IP 模式，新增配置项 EnableMultiIngress
  cloudprovider/volcengine/clb.go
  cloudprovider/volcengine/clb_test.go
Labels: lgtm, size/L

#257 bugfix: consider preDelete pods when scaling
  pkg/controllers/gameserverset/gameserverset_manager.go
  pkg/controllers/gameserverset/gameserverset_manager_test.go
Labels: size/L

#259 enhance: network trigger time adapts to different time zones
  config/default/manager_webhook_patch.yaml
  pkg/controllers/gameserver/gameserver_manager.go
Labels: size/S

#260 bugfix(Kubernetes-HostPort): allow pod update when node notfound
  cloudprovider/kubernetes/hostPort.go
Labels: size/XS

#261 add huawei cloud EIP support, enhanced support for ELB
  cloudprovider/hwcloud/eip_cce.go
  cloudprovider/hwcloud/eip_cce_test.go
  cloudprovider/hwcloud/elb_cce.go
  cloudprovider/hwcloud/elb_cce_test.go
  cloudprovider/hwcloud/elb_test_mock.go
  cloudprovider/hwcloud/hwcloud.go
  cloudprovider/options/hwcloud_options.go
  config/manager/config.toml
  docs/en/user_manuals/network.md
  docs/中文/用户手册/网络模型.md
  go.mod
  go.sum
Labels: size/XXL, lgtm

#263 deps: update codecov version for github workflow
  .github/workflows/ci.yaml
Labels: size/XS

#265 deps: update e2e kruise version to 1.8
  .github/workflows/e2e-1.26.yaml
  .github/workflows/e2e-1.30.yaml
Labels: size/XS
