Repository openkruise/kruise-game, pull requests merged in 2025-06, with the labels that each got.

#230 enhance: Kubernetes-HostPort support container port same as host
  cloudprovider/kubernetes/hostPort.go
Labels: size/S

#224 enhance: AlibabaCloud-SLB-SharedPort plugin support managed services
  cloudprovider/alibabacloud/slb_sp.go
  cloudprovider/alibabacloud/slb_sp_test.go
Labels: size/M

#237 fix go-lint err
  cloudprovider/options/alibabacloud_options.go
Labels: size/XS

#233 fix:add pod create time in svc
  cloudprovider/volcengine/clb.go
Labels: lgtm, size/XS

#244 feat(Kubernetes-HostPort): support TCPUDP protocol
  cloudprovider/kubernetes/hostPort.go
Labels: lgtm, size/M

#238 feat: add annotation of state-last-changed-time
  apis/v1alpha1/gameserver_types.go
  pkg/controllers/gameserver/gameserver_manager.go
Labels: size/XS

#247 feat: support user-defined number of controller workers
  pkg/controllers/gameserver/gameserver_controller.go
  pkg/controllers/gameserverset/gameserverset_controller.go
Labels: size/S

#246 feat: support new plugin named AlibabaCloud-AutoNLBs
  cloudprovider/alibabacloud/auto_nlbs.go
  cloudprovider/alibabacloud/auto_nlbs_test.go
  pkg/util/slice.go
Labels: size/XL
